//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigBook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BigBook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base stream is currently null..
        /// </summary>
        internal static string BaseStreamCurrentlyNullError {
            get {
                return ResourceManager.GetString("BaseStreamCurrentlyNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The size and error rate values would result in an array of &gt; int.MaxValue length..
        /// </summary>
        internal static string BloomFilterCapacity {
            get {
                return ResourceManager.GetString("BloomFilterCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to denominator can&apos;t be int.MinValue.
        /// </summary>
        internal static string DenominatorIntMinError {
            get {
                return ResourceManager.GetString("DenominatorIntMinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FormatPattern is not valid.
        /// </summary>
        internal static string FormatPatternIsNotValidError {
            get {
                return ResourceManager.GetString("FormatPatternIsNotValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid 7-bit encoded integer in stream..
        /// </summary>
        internal static string Invalid7bitIntInStreamError {
            get {
                return ResourceManager.GetString("Invalid7bitIntInStreamError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both matrices must be the same dimensions..
        /// </summary>
        internal static string MatrixNotSameSizeError {
            get {
                return ResourceManager.GetString("MatrixNotSameSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The determinant can not be calculated for a non square matrix.
        /// </summary>
        internal static string MatrixNotSquareError {
            get {
                return ResourceManager.GetString("MatrixNotSquareError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.Body is not a MemberExpression.
        /// </summary>
        internal static string NotAMemberExpression {
            get {
                return ResourceManager.GetString("NotAMemberExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PropertyInfo can&apos;t be null.
        /// </summary>
        internal static string PropertyInfoCantBeNull {
            get {
                return ResourceManager.GetString("PropertyInfoCantBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is not from the declaring class type specified.
        /// </summary>
        internal static string PropertyNotOfDeclaringType {
            get {
                return ResourceManager.GetString("PropertyNotOfDeclaringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property is not of the type specified.
        /// </summary>
        internal static string PropertyOfWrongType {
            get {
                return ResourceManager.GetString("PropertyOfWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reader.FieldCount needs to have at least 0 fields.
        /// </summary>
        internal static string ReaderFieldCountError {
            get {
                return ResourceManager.GetString("ReaderFieldCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add item to circular buffer because the buffer is full.
        /// </summary>
        internal static string RingBufferFullError {
            get {
                return ResourceManager.GetString("RingBufferFullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is not readable.
        /// </summary>
        internal static string StreamNotReadableError {
            get {
                return ResourceManager.GetString("StreamNotReadableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream is not writable.
        /// </summary>
        internal static string StreamNotWritableError {
            get {
                return ResourceManager.GetString("StreamNotWritableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value can not be MinValue.
        /// </summary>
        internal static string ValueCanNotBeMin {
            get {
                return ResourceManager.GetString("ValueCanNotBeMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value can not be 2147483648.
        /// </summary>
        internal static string ValueCantBeValue {
            get {
                return ResourceManager.GetString("ValueCantBeValue", resourceCulture);
            }
        }
    }
}
